[font]
size = 13.0

[font.normal]
family = "Hack Nerd Font"

[window.dimensions]
columns = 100
lines = 24

[colors.bright]
black = "#5C6A72"
blue = "#3A94C5"
cyan = "#35A77C"
green = "#8DA101"
magenta = "#DF69BA"
red = "#F85552"
white = "#DFDDC8"
yellow = "#DFA000"

[colors.cursor]
cursor = "#919191"
text = "#000000"

[colors.normal]
black = "#4B565C"
blue = "#7FBBB3"
cyan = "#83C092"
green = "#A7C080"
magenta = "#D699B6"
red = "#E67E80"
white = "#D3C6AA"
yellow = "#DBBC7F"

[colors.primary]
background = "#2D353B"
foreground = "#D3C6AA"
